Adds a searchable map to upload page
chanjonathan/SPS-Team22-Project pull request #14
Opened 2022-07-08 05:51 UTC by michelleli18

There is now a map that can be searched for locations on upload page. Can navigate between upload page and main page with buttons now. This commit does not include javascript or servlet parts of the page yet, those are still work in progress. Just pushing so that everyone gets an updated page to better work with!

2022-07-12 23:29 UTC, EvanJuV requested changes

2022-07-12 23:29 UTC, EvanJuV commented on project/src/main/java/com/google/sps/servlets/UploadReport.java
> +// @Override
Do we want to Override or not? If we don't need it anymore, please delete it.

2022-07-12 23:29 UTC, EvanJuV commented on project/src/main/webapp/upload-page/upload.html
> +<<<<<<< HEAD
Please resolve this diff by selecting the HTML sections that you want to keep. The section between the <<< HEAD and === markers are your local changes, and the section between === and >>>> ec2c0ce4d528... is how this same section looks in the commit your merging.

2022-07-12 23:29 UTC, EvanJuV commented on project/src/main/webapp/upload-page/upload.html
> +<<<<<<< HEAD
Please resolve this other diff.

2022-07-12 23:29 UTC, EvanJuV commented on project/src/main/webapp/upload-page/upload_script.js
> +<<<<<<< HEAD
Resolve this diff.

2022-07-12 23:29 UTC, EvanJuV commented on project/src/main/webapp/upload-page/upload_script.js
> +<<<<<<< HEAD
Resolve this other diff.

2022-07-12 23:29 UTC, EvanJuV commented on project/src/main/webapp/upload-page/upload_script.js
> +<<<<<<< HEAD
This one as well.

2022-07-12 23:29 UTC, EvanJuV commented on project/src/main/webapp/upload-page/upload_script.js
> +<<<<<<< HEAD
Also this one please.

2022-07-12 23:29 UTC, EvanJuV commented on project/src/main/webapp/upload-page/upload_style.css
> +<<<<<<< HEAD
And finally this one.

2022-07-14 08:06 UTC, michelleli18 commented
Updated with the newest commit just now! It resolved all the diffs and also took care of the required fields for the survey

2022-07-19 00:15 UTC, EvanJuV requested changes

2022-07-19 00:15 UTC, EvanJuV commented on project/src/main/webapp/upload-page/upload.html
> +        <form action="../index.html">
I think you can just do "/index.html" as that's the absolute path of the index.

2022-07-19 00:15 UTC, EvanJuV commented on project/src/main/webapp/upload-page/upload.html
> +                <li id = "inline-textbox">
I see this id="inline-textbox" being used more than once. In CSS, IDs are used to target a single specific element. If you want to target multiple elements use a class or change directly the element type.

Also please remove the spaces before and after =. 

Apply changes to any other li element.

2022-07-21 19:19 UTC, chanjonathan commented
can we merge this to main?

2022-07-22 21:27 UTC, EvanJuV approved these changes
LGTM

2022-07-22 21:27 UTC, merged