Break down get methods
chanjonathan/SPS-Team22-Project pull request #16
Opened 2022-07-08 08:49 UTC by chanjonathan

2022-07-12 22:01 UTC, EvanJuV requested changes
Nice Jonathan and thanks for the cleanup! Please take a look at my two comments. Please also ping me to review your changes again as I don't read my personal email that often.

2022-07-12 22:01 UTC, EvanJuV commented on project/pom.xml
> +        <googleCloudProjectId>jchan-sps-summer22</googleCloudProjectId>
Let's try to keep the googleCloudProjectId as summer22-sps-22. You can still deploy to your own website, just remember to change this back before pushing.

2022-07-12 22:01 UTC, EvanJuV commented on project/src/main/java/com/google/sps/servlets/DeleteServlet.java
> +    private String getParameter(HttpServletRequest request, String name, String defaultValue) {
Given that you're putting this function in all your servlets, you could add it to a shared utility library.

2022-07-13 22:27 UTC, chanjonathan commented on project/pom.xml
> +        <googleCloudProjectId>jchan-sps-summer22</googleCloudProjectId>
fixed

2022-07-13 22:28 UTC, chanjonathan commented on project/src/main/java/com/google/sps/servlets/DeleteServlet.java
> +    private String getParameter(HttpServletRequest request, String name, String defaultValue) {
added a utilities/Http class

2022-07-13 23:17 UTC, EvanJuV approved these changes

2022-07-13 23:18 UTC, merged